# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Install dependencies and build app for testing"
  lane :build_for_testing do
    cocoapods
    scan(
      clean: true,
      build_for_testing: true,
      derived_data_path: "DerivedData/"
    )
  end

  desc "Run tests on build app"
  lane :run_tests_without_building do
    scan(
      derived_data_path: "DerivedData/",
      test_without_building: true
    )
  end
end
